version: '3'
services:
  frontend:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
networks:
  default:
    driver: bridge

