version: '3'
services:
  frontend:
    build:
      context: ./reactapp
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./reactapp:/usr/src/app
      -  /usr/src/app/node_modules
    networks:
      - frontend-backend-network
    depends_on:
      - backend

  backend:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nodeapi:/usr/src/app
      -  /usr/src/app/node_modules
    networks:
      - app-network
      - internal-network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal-network

networks:
  app-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
